del "Data\*.txt" /S /Q

"%userprofile%\Apps\VX Ace Translator\VXAceTranslator.exe" -d "%CD%" -o "%CD%\Data"

del "Data\0 - .rb" /S /Q
del "Data\1 -  Modules.rb" /S /Q
del "Data\10 - Game_Temp.rb" /S /Q
del "Data\100 - Scene_Base.rb" /S /Q
del "Data\101 - Scene_Title.rb" /S /Q
del "Data\102 - Scene_Map.rb" /S /Q
del "Data\103 - Scene_MenuBase.rb" /S /Q
del "Data\104 - Scene_Menu.rb" /S /Q
del "Data\105 - Scene_ItemBase.rb" /S /Q
del "Data\106 - Scene_Item.rb" /S /Q
del "Data\107 - Scene_Skill.rb" /S /Q
del "Data\108 - Scene_Equip.rb" /S /Q
del "Data\109 - Scene_Status.rb" /S /Q
del "Data\11 - Game_System.rb" /S /Q
del "Data\110 - Scene_File.rb" /S /Q
del "Data\111 - Scene_Save.rb" /S /Q
del "Data\112 - Scene_Load.rb" /S /Q
del "Data\113 - Scene_End.rb" /S /Q
del "Data\114 - Scene_Shop.rb" /S /Q
del "Data\115 - Scene_Name.rb" /S /Q
del "Data\116 - Scene_Debug.rb" /S /Q
del "Data\117 - Scene_Battle.rb" /S /Q
del "Data\118 - Scene_Gameover.rb" /S /Q
del "Data\119 - .rb" /S /Q
del "Data\12 - Game_Timer.rb" /S /Q
del "Data\120 -  Materials.rb" /S /Q
del "Data\121 - Logo.rb" /S /Q
del "Data\122 - ( Insert here ).rb" /S /Q
del "Data\13 - Game_Message.rb" /S /Q
del "Data\135 - .rb" /S /Q
del "Data\136 -  Main Process.rb" /S /Q
del "Data\137 - Main.rb" /S /Q
del "Data\138 - .rb" /S /Q
del "Data\14 - Game_Switches.rb" /S /Q
del "Data\15 - Game_Variables.rb" /S /Q
del "Data\16 - Game_SelfSwitches.rb" /S /Q
del "Data\17 - Game_Screen.rb" /S /Q
del "Data\18 - Game_Picture.rb" /S /Q
del "Data\19 - Game_Pictures.rb" /S /Q
del "Data\2 - Vocab.rb" /S /Q
del "Data\20 - Game_BaseItem.rb" /S /Q
del "Data\21 - Game_Action.rb" /S /Q
del "Data\22 - Game_ActionResult.rb" /S /Q
del "Data\23 - Game_Battlerb" /S /Qase.rb" /S /Q
del "Data\24 - Game_Battler.rb" /S /Q
del "Data\25 - Game_Actor.rb" /S /Q
del "Data\26 - Game_Enemy.rb" /S /Q
del "Data\27 - Game_Actors.rb" /S /Q
del "Data\28 - Game_Unit.rb" /S /Q
del "Data\29 - Game_Party.rb" /S /Q
del "Data\3 - Sound.rb" /S /Q
del "Data\30 - Game_Troop.rb" /S /Q
del "Data\31 - Game_Map.rb" /S /Q
del "Data\32 - Game_CommonEvent.rb" /S /Q
del "Data\33 - Game_Characterb" /S /Qase.rb" /S /Q
del "Data\34 - Game_Character.rb" /S /Q
del "Data\35 - Game_Player.rb" /S /Q
del "Data\36 - Game_Follower.rb" /S /Q
del "Data\37 - Game_Followers.rb" /S /Q
del "Data\38 - Game_Vehicle.rb" /S /Q
del "Data\39 - Game_Event.rb" /S /Q
del "Data\4 - Cache.rb" /S /Q
del "Data\40 - Game_Interpreter.rb" /S /Q
del "Data\41 - .rb" /S /Q
del "Data\42 -  Sprites.rb" /S /Q
del "Data\43 - Sprite_Base.rb" /S /Q
del "Data\44 - Sprite_Character.rb" /S /Q
del "Data\45 - Sprite_Battler.rb" /S /Q
del "Data\46 - Sprite_Picture.rb" /S /Q
del "Data\47 - Sprite_Timer.rb" /S /Q
del "Data\48 - Spriteset_Weather.rb" /S /Q
del "Data\49 - Spriteset_Map.rb" /S /Q
del "Data\5 - DataManager.rb" /S /Q
del "Data\50 - Spriteset_Battle.rb" /S /Q
del "Data\51 - .rb" /S /Q
del "Data\52 -  Windows.rb" /S /Q
del "Data\53 - Window_Base.rb" /S /Q
del "Data\54 - Window_Selectable.rb" /S /Q
del "Data\55 - Window_Command.rb" /S /Q
del "Data\56 - Window_HorzCommand.rb" /S /Q
del "Data\57 - Window_Help.rb" /S /Q
del "Data\58 - Window_Gold.rb" /S /Q
del "Data\59 - Window_MenuCommand.rb" /S /Q
del "Data\6 - SceneManager.rb" /S /Q
del "Data\60 - Window_MenuStatus.rb" /S /Q
del "Data\61 - Window_MenuActor.rb" /S /Q
del "Data\62 - Window_ItemCategory.rb" /S /Q
del "Data\63 - Window_ItemList.rb" /S /Q
del "Data\64 - Window_SkillCommand.rb" /S /Q
del "Data\65 - Window_SkillStatus.rb" /S /Q
del "Data\66 - Window_SkillList.rb" /S /Q
del "Data\67 - Window_EquipStatus.rb" /S /Q
del "Data\68 - Window_EquipCommand.rb" /S /Q
del "Data\69 - Window_EquipSlot.rb" /S /Q
del "Data\7 - BattleManager.rb" /S /Q
del "Data\70 - Window_EquipItem.rb" /S /Q
del "Data\71 - Window_Status.rb" /S /Q
del "Data\72 - Window_SaveFile.rb" /S /Q
del "Data\73 - Window_ShopCommand.rb" /S /Q
del "Data\74 - Window_ShopBuy.rb" /S /Q
del "Data\75 - Window_ShopSell.rb" /S /Q
del "Data\76 - Window_ShopNumber.rb" /S /Q
del "Data\77 - Window_ShopStatus.rb" /S /Q
del "Data\78 - Window_NameEdit.rb" /S /Q
del "Data\79 - Window_NameInput.rb" /S /Q
del "Data\8 - .rb" /S /Q
del "Data\80 - Window_ChoiceList.rb" /S /Q
del "Data\81 - Window_NumberInput.rb" /S /Q
del "Data\82 - Window_KeyItem.rb" /S /Q
del "Data\83 - Window_Message.rb" /S /Q
del "Data\84 - Window_ScrollText.rb" /S /Q
del "Data\85 - Window_MapName.rb" /S /Q
del "Data\86 - Window_BattleLog.rb" /S /Q
del "Data\87 - Window_PartyCommand.rb" /S /Q
del "Data\88 - Window_ActorCommand.rb" /S /Q
del "Data\89 - Window_BattleStatus.rb" /S /Q
del "Data\9 -  Game Objects.rb" /S /Q
del "Data\90 - Window_BattleActor.rb" /S /Q
del "Data\91 - Window_BattleEnemy.rb" /S /Q
del "Data\92 - Window_BattleSkill.rb" /S /Q
del "Data\93 - Window_BattleItem.rb" /S /Q
del "Data\94 - Window_TitleCommand.rb" /S /Q
del "Data\95 - Window_GameEnd.rb" /S /Q
del "Data\96 - Window_DebugLeft.rb" /S /Q
del "Data\97 - Window_DebugRight.rb" /S /Q
del "Data\98 - .rb" /S /Q
del "Data\99 -  Scenes.rb" /S /Q